import { colors } from "../../constants/colors";

export const styles = {
  root: {
    paddingLeft: 50,
    paddingRight: 50,
    paddingTop: 30,
    backgroundColor: colors.orangeLight,
  },
  title: { fontSize: 24, color: colors.black, fontFamily: "Inter700" },
  rootContainer: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    marginTop: 20,
    // backgroundColor  : "#ccc",
  },
  colorContainer: {
    width: "25vw",
    padding: 20,
    borderRadius: 10,
    boxShadow: "2px 2px 6px rgba(0, 0, 0, 0.2)",
  },
  colorTitle: {
    fontSize: 14,
    color: colors.black,
    fontFamily: "Inter600",
  },
  colorSubtitle: {
    fontSize: 13,
    color: colors.black,
    fontFamily: "Inter400",
  },
  category: { marginTop: 20 },
  categoryTitle: {
    fontFamily: "Inter400",
    fontSize: 13,
    color: colors.black100,
  },
  inputContainer: {
    display: "flex",
    flexDirection: "row",
    gap: 20,
    marginTop: 10,
  },
  input: {
    flex: 1,
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 0.6,
    borderColor: colors.grey,
    fontFamily: "Inter400",
    fontSize: 13,
    color: colors.black100,
    padding: 10,
  },
  categoryColor: {
    backgroundColor: colors.red200,
    width: 60,
    height: 30,
    borderRadius: 10,
  },
  button: { marginTop: 20, gap: 10, display: "flex", padding: 10 },
  exclusiveRoot: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    paddingBottom: 10,
  },
  exclusiveContainer: {
    boxShadow: "2px 2px 6px rgba(0, 0, 0, 0.2)",
    borderRadius: 15,
    marginBottom: 20,
    padding: 20,
  },
  exclusiveTitle: { fontSize: 14, color: colors.black, fontFamily: "Inter600" },
  exclusiveSubtitle: {
    fontSize: 13,
    color: colors.black,
    fontFamily: "Inter400",
  },
  custom: {
    width: "30vw",
    boxShadow: "2px 2px 6px rgba(0, 0, 0, 0.2)",
    paddingLeft: 20,
    paddingTop: 20,
    borderRadius: 15,
  },
  linkContainer: {
    display: "flex",
    flexDirection: "column",
    marginTop: 20,
    marginRight: 20,
  },
  linkTitle: {
    paddingTop: 20,
    paddingBottom: 20,
    fontFamily: "Inter400",
    fontSize: 13,
    color: colors.black100,
  },
  linkInput: {
    height: "160px",
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 0.5,
    borderColor: colors.grey,
    fontFamily: "Inter400",
    fontSize: 14,
    color: colors.black100,
    padding: 10,

    verticalAlign: "text-top",
  },
};
