import { colors } from "../../constants/colors";

export const styles = {
  root: {
    backgroundColor: colors.yellow500,
    paddingLeft: 50,
    paddingRight: 50,
    paddingBottom: 40,
    paddingTop: 30,
  },
  rootContainer: {
    marginTop: 40,
    display: "flex",
    gap: 10,
  },
  title: { fontFamily: "Inter700", fontSize: 24, color: colors.black },
  tab1: {
    padding: 10,
    backgroundColor: colors.white,
    marginRight: 5,
    borderRadius: 10,
    fontFamily: "Inter600",
    fontSize: 13,
    color: colors.black,
  },
  tab: {
    backgroundColor: colors.white,
    padding: 12,
    borderRadius: 10,
    marginLeft: 5,
    marginRight: 5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    fontFamily: "Inter600",
    fontSize: 13,
    color: colors.black,
  },
  titleContainer: {
    backgroundColor: colors.white,
    display: "flex",
    flexDirection: "column",
    flex: 1,
    padding: 20,
    borderRadius: 15,
    boxShadow: "2px 2px 6px rgba(0, 0, 0, 0.2)",
  },
  orderContainer: { display: "flex" },
  order: {
    display: "flex",
    flex: 1,
    fontFamily: "Inter600",
    fontSize: 14,
    color: colors.black,
  },
  total: {
    fontFamily: "Inter400",
    fontSize: 14,
    color: colors.black,
  },
  deliveredContainer: { display: "flex", flexDirection: "row" },
  status: {
    fontSize: 13,
    color: colors.black,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 10,
    marginRight: 10,
    backgroundColor: colors.white200,
    padding: 10,
    fontFamily: "Inter600",
    fontSize: 13,
    color: colors.black,
  },
  starFacts: { fontSize: 14, fontFamily: "Inter600" },
  starFactsSubtitle: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    fontFamily: "Inter400",
    fontSize: 13,
  },
  trackingContainer: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    padding: 20,
    backgroundColor: colors.white,
    borderRadius: 10,
    boxShadow: "2px 2px 6px rgba(0, 0, 0, 0.2)",
  },
  trackingTitle: { fontSize: 14, color: colors.black, fontFamily: "Inter600" },
  trackingSubtitle: {
    fontSize: 13,
    color: colors.black,
    fontFamily: "Inter400",
  },
  trackingOrderContainer: {
    backgroundColor: colors.yellow400,
    borderRadius: 5,
    padding: 20,
    marginBottom: 10,
    paddingRight: 40,
  },
  trackingOrderContainer2: {
    backgroundColor: colors.orange100,
    borderRadius: 5,
    padding: 20,
    marginTop: 10,
    paddingRight: 40,
  },
  trackingOrderTitle: {
    fontSize: 12,
    fontFamily: "Inter500",
    color: colors.black,
  },
  trackingOrderAmt: {
    display: "flex",
    flex: 1,
    fontSize: 36,
    fontFamily: "Inter700",
    color: colors.black,
  },
  trackingOrderAmtContainer: {
    display: "flex",
    flexDirection: "row",
    paddingTop: 10,
    paddingBottom: 10,
  },
};
